In [1]:
import pandas as pd
import numpy as np

In [13]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_2/individual_results'

data = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/results_rank_{i}.csv'
    try:
        # Attempt to read the CSV file
        df = pd.read_csv(file_path, header=0)
    except FileNotFoundError:
        # If the file does not exist, skip to the next iteration
        print(f"File {file_path} not found. Skipping.")
        continue
    print("Number of Models in file", i, ":", len(df))
    data = pd.concat([data, df], ignore_index=True)

Number of Models in file 0 : 10000
Number of Models in file 1 : 10000
Number of Models in file 2 : 10000
Number of Models in file 3 : 10000
Number of Models in file 4 : 10000
Number of Models in file 5 : 10000
Number of Models in file 6 : 10000
Number of Models in file 7 : 10000
Number of Models in file 8 : 10000
Number of Models in file 9 : 10000
Number of Models in file 10 : 10000
Number of Models in file 11 : 10000
Number of Models in file 12 : 10000
Number of Models in file 13 : 10000
Number of Models in file 14 : 10000
Number of Models in file 15 : 10000
Number of Models in file 16 : 10000
Number of Models in file 17 : 10000
Number of Models in file 18 : 10000
Number of Models in file 19 : 10000
Number of Models in file 20 : 10000
Number of Models in file 21 : 10000
Number of Models in file 22 : 10000
Number of Models in file 23 : 10000
Number of Models in file 24 : 10000
Number of Models in file 25 : 10000
Number of Models in file 26 : 10000
Number of Models in file 27 : 10000
Number of Models in file 28 : 10000
Number of Models in file 29 : 10000
Number of Models in file 30 : 10000
Number of Models in file 31 : 10000
Number of Models in file 32 : 10000
Number of Models in file 33 : 10000
Number of Models in file 34 : 10000
Number of Models in file 35 : 10000
Number of Models in file 36 : 10000
Number of Models in file 37 : 10000
Number of Models in file 38 : 10000
Number of Models in file 39 : 10000
Number of Models in file 40 : 10000
Number of Models in file 41 : 10000
Number of Models in file 42 : 10000
Number of Models in file 43 : 10000
Number of Models in file 44 : 10000
Number of Models in file 45 : 10000
Number of Models in file 46 : 10000
Number of Models in file 47 : 10000
Number of Models in file 48 : 10000
Number of Models in file 49 : 10000
Number of Models in file 50 : 10000
Number of Models in file 51 : 10000
Number of Models in file 52 : 10000
Number of Models in file 53 : 10000
Number of Models in file 54 : 10000
Number of Models in file 55 : 10000
Number of Models in file 56 : 10000
Number of Models in file 57 : 10000
Number of Models in file 58 : 10000
Number of Models in file 59 : 10000
Number of Models in file 60 : 10000
Number of Models in file 61 : 10000
Number of Models in file 62 : 10000
Number of Models in file 63 : 10000
Number of Models in file 64 : 10000
Number of Models in file 65 : 10000
Number of Models in file 66 : 10000
Number of Models in file 67 : 10000
Number of Models in file 68 : 10000
Number of Models in file 69 : 10000
Number of Models in file 70 : 10000
Number of Models in file 71 : 10000
Number of Models in file 72 : 10000
Number of Models in file 73 : 10000
Number of Models in file 74 : 10000
Number of Models in file 75 : 10000
Number of Models in file 76 : 10000
Number of Models in file 77 : 10000
Number of Models in file 78 : 10000
Number of Models in file 79 : 10000
Number of Models in file 80 : 10000
Number of Models in file 81 : 10000
Number of Models in file 82 : 10000
Number of Models in file 83 : 10000
Number of Models in file 84 : 10000
Number of Models in file 85 : 10000
Number of Models in file 86 : 10000
Number of Models in file 87 : 10000
Number of Models in file 88 : 10000
Number of Models in file 89 : 9600
Number of Models in file 90 : 7700
Number of Models in file 91 : 8900
Number of Models in file 92 : 9500
Number of Models in file 93 : 9100
Number of Models in file 94 : 8900
Number of Models in file 95 : 9000
Number of Models in file 96 : 9300
Number of Models in file 97 : 8500
Number of Models in file 98 : 8200
Number of Models in file 99 : 8400

In [17]:
data

,m,n,o,num_images,pos_rms,mag_rms,avg_mag_per,chi2,source_x,source_y,...,POW_e,POW_$θ_{e}$,POW_$r_{Ein}$,POW_$\gamma$ (PWI),"PERT_$z_{s,fid}$",PERT_x,PERT_y,PERT_$\gamma$,PERT_$θ_{\gamma}$,PERT_$\kappa$
0,0.001,0.00000,-0.5,5,0.088447,185.634258,2228.827552,2434.981,0.162586,0.031560,...,0.004600,12.010590,0.617548,2.299996,1.0,0.0,0.0,0.001,0.00000,-0.5
1,0.001,3.63636,-0.5,4,0.052036,18.227642,290.482580,2787.826,0.149783,0.010994,...,0.057534,3.693356,0.628586,2.299993,1.0,0.0,0.0,0.001,3.63636,-0.5
2,0.001,7.27273,-0.5,4,0.052590,18.662187,295.453620,2788.300,0.149412,0.010916,...,0.056454,3.641083,0.628987,2.300000,1.0,0.0,0.0,0.001,7.27273,-0.5
3,0.001,10.90909,-0.5,4,0.052699,18.281831,291.385556,2789.506,0.150441,0.010936,...,0.057291,3.467977,0.628246,2.299986,1.0,0.0,0.0,0.001,10.90909,-0.5
4,0.001,14.54545,-0.5,4,0.053154,16.539317,273.180396,2813.109,0.155761,0.011413,...,0.060913,3.115380,0.623610,2.300000,1.0,0.0,0.0,0.001,14.54545,-0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987095,0.084,345.45455,0.5,2,0.238763,101.149731,3611.223302,86653.230,-0.011972,0.038884,...,0.378999,73.489490,0.371481,2.299950,1.0,0.0,0.0,0.084,345.45450,0.5
987096,0.084,349.09091,0.5,2,0.244830,88.278023,3161.162733,86109.800,-0.015354,0.037326,...,0.364968,76.406980,0.371752,2.299999,1.0,0.0,0.0,0.084,349.09090,0.5
987097,0.084,352.72727,0.5,4,0.287431,39.434768,480.005125,37535.780,-0.095823,-0.016502,...,0.252848,57.806630,0.402907,2.299945,1.0,0.0,0.0,0.084,352.72730,0.5
987098,0.084,356.36364,0.5,4,0.293347,34.158420,433.308268,37828.920,-0.098317,-0.019937,...,0.193345,58.130280,0.402479,2.299999,1.0,0.0,0.0,0.084,356.36360,0.5
987099,0.084,360.00000,0.5,4,0.258411,47.451196,550.433432,34366.760,-0.079580,-0.016297,...,0.183774,77.708310,0.385148,2.299995,1.0,0.0,0.0,0.084,360.00000,0.5

In [16]:
data.to_csv('/Volumes/T7 Shield/Simulation Output/System 2/Sim 10_absmags.csv', index=False)

In [12]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_2/progress_status'

progress = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/worker_{i}.status'
    try:
        df = pd.read_csv(file_path, header=None)
    except FileNotFoundError:
        print(f"File {file_path} not found. Skipping.")
        continue
    progress = pd.concat([progress, df], ignore_index=True)

In [7]:
progress

        0
0   10000
1   10000
2   10000
3   10000
4   10000
..    ...
95   9000
96   9300
97   8500
98   8200
99   8400

[100 rows x 1 columns]