In [1]:
import pandas as pd
import numpy as np

In [2]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_4/individual_results'

data = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/results_rank_{i}.csv'
    try:
        # Attempt to read the CSV file
        df = pd.read_csv(file_path, header=0)
    except FileNotFoundError:
        # If the file does not exist, skip to the next iteration
        print(f"File {file_path} not found. Skipping.")
        continue
    print("Number of Models in file", i, ":", len(df))
    data = pd.concat([data, df], ignore_index=True)

Number of Models in file 0 : 10000
Number of Models in file 1 : 10000
Number of Models in file 2 : 10000
Number of Models in file 3 : 10000
Number of Models in file 4 : 10000
Number of Models in file 5 : 10000
Number of Models in file 6 : 10000
Number of Models in file 7 : 10000
Number of Models in file 8 : 10000
Number of Models in file 9 : 10000
Number of Models in file 10 : 10000
Number of Models in file 11 : 10000
Number of Models in file 12 : 10000
Number of Models in file 13 : 10000
Number of Models in file 14 : 10000
Number of Models in file 15 : 10000
Number of Models in file 16 : 10000
Number of Models in file 17 : 10000
Number of Models in file 18 : 10000
Number of Models in file 19 : 10000
Number of Models in file 20 : 10000
Number of Models in file 21 : 10000
Number of Models in file 22 : 10000
Number of Models in file 23 : 10000
Number of Models in file 24 : 10000
Number of Models in file 25 : 10000
Number of Models in file 26 : 10000
Number of Models in file 27 : 10000
Number of Models in file 28 : 10000
Number of Models in file 29 : 10000
Number of Models in file 30 : 10000
Number of Models in file 31 : 10000
Number of Models in file 32 : 10000
Number of Models in file 33 : 10000
Number of Models in file 34 : 10000
Number of Models in file 35 : 10000
Number of Models in file 36 : 10000
Number of Models in file 37 : 10000
Number of Models in file 38 : 10000
Number of Models in file 39 : 10000
Number of Models in file 40 : 10000
Number of Models in file 41 : 10000
Number of Models in file 42 : 10000
Number of Models in file 43 : 10000
Number of Models in file 44 : 10000
Number of Models in file 45 : 10000
Number of Models in file 46 : 10000
Number of Models in file 47 : 10000
Number of Models in file 48 : 10000
Number of Models in file 49 : 10000
Number of Models in file 50 : 10000
Number of Models in file 51 : 10000
Number of Models in file 52 : 10000
Number of Models in file 53 : 10000
Number of Models in file 54 : 10000
Number of Models in file 55 : 10000
Number of Models in file 56 : 10000
Number of Models in file 57 : 10000
Number of Models in file 58 : 10000
Number of Models in file 59 : 10000
Number of Models in file 60 : 10000
Number of Models in file 61 : 10000
Number of Models in file 62 : 10000
Number of Models in file 63 : 10000
Number of Models in file 64 : 10000
Number of Models in file 65 : 10000
Number of Models in file 66 : 10000
Number of Models in file 67 : 10000
Number of Models in file 68 : 10000
Number of Models in file 69 : 10000
Number of Models in file 70 : 10000
Number of Models in file 71 : 10000
Number of Models in file 72 : 10000
Number of Models in file 73 : 10000
Number of Models in file 74 : 10000
Number of Models in file 75 : 10000
Number of Models in file 76 : 10000
Number of Models in file 77 : 10000
Number of Models in file 78 : 10000
Number of Models in file 79 : 10000
Number of Models in file 80 : 10000
Number of Models in file 81 : 10000
Number of Models in file 82 : 10000
Number of Models in file 83 : 10000
Number of Models in file 84 : 10000
Number of Models in file 85 : 10000
Number of Models in file 86 : 10000
Number of Models in file 87 : 10000
Number of Models in file 88 : 10000
Number of Models in file 89 : 10000
Number of Models in file 90 : 10000
Number of Models in file 91 : 10000
Number of Models in file 92 : 10000
Number of Models in file 93 : 10000
Number of Models in file 94 : 10000
Number of Models in file 95 : 10000
Number of Models in file 96 : 10000
Number of Models in file 97 : 10000
Number of Models in file 98 : 10000
Number of Models in file 99 : 10000

In [3]:
data

,m,n,o,num_images,pos_rms,mag_rms,avg_mag_per,chi2,source_x,source_y,...,SIE_y,SIE_e,SIE_$θ_{e}$,SIE_$r_{core}$,"PERT_$z_{s,fid}$",PERT_x,PERT_y,PERT_$\gamma$,PERT_$θ_{\gamma}$,PERT_$\kappa$
0,0.001,0.00000,0.0,4,0.064748,18.993602,370.768392,20318.62,20.81337,20.83248,...,20.82609,0.059481,-4.765629,0.0,1.0,20.78,20.78,0.001,0.00000,0.0
1,0.001,36.03604,0.0,4,0.071009,7.886166,219.269079,20838.13,20.81688,20.84788,...,20.83896,0.100446,-4.935638,0.0,1.0,20.78,20.78,0.001,36.03604,0.0
2,0.001,72.07207,0.0,4,0.071078,7.953516,220.316904,20871.80,20.81718,20.84798,...,20.83919,0.102768,-4.496991,0.0,1.0,20.78,20.78,0.001,72.07207,0.0
3,0.001,108.10811,0.0,4,0.064551,19.590891,379.098722,20359.94,20.81315,20.83202,...,20.82585,0.062911,-3.643414,0.0,1.0,20.78,20.78,0.001,108.10810,0.0
4,0.001,144.14414,0.0,4,0.070974,7.928211,219.993861,20818.43,20.81674,20.84796,...,20.83904,0.099312,-3.559363,0.0,1.0,20.78,20.78,0.001,144.14410,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.100,215.85586,0.0,2,0.077421,179.644214,2106.474755,31749.88,20.78594,20.81111,...,20.80790,0.261844,-54.038730,0.0,1.0,20.78,20.78,0.100,215.85590,0.0
999996,0.100,251.89189,0.0,4,0.085715,14.049670,315.651408,32965.97,20.80258,20.79525,...,20.80324,0.212631,-22.126460,0.0,1.0,20.78,20.78,0.100,251.89190,0.0
999997,0.100,287.92793,0.0,4,0.089395,17.543964,366.408082,31977.79,20.82060,20.79937,...,20.80282,0.226032,22.474100,0.0,1.0,20.78,20.78,0.100,287.92790,0.0
999998,0.100,323.96396,0.0,4,0.381003,1097.293846,12753.444963,33422.24,20.83077,20.81641,...,20.80665,0.254628,52.690930,0.0,1.0,20.78,20.78,0.100,323.96400,0.0
999999,0.100,360.00000,0.0,4,0.057065,3.093656,87.571074,24835.13,20.82032,20.80280,...,20.75628,0.000008,11.803620,0.0,1.0,20.78,20.78,0.100,360.00000,0.0

In [4]:
data.to_csv('/Volumes/T7 Shield/Simulation Output/System 1/Sim 4_absmags.csv', index=False)

In [ ]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_4/progress_status'

progress = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/worker_{i}.status'
    try:
        df = pd.read_csv(file_path, header=None)
    except FileNotFoundError:
        print(f"File {file_path} not found. Skipping.")
        continue
    progress = pd.concat([progress, df], ignore_index=True)

In [11]:
progress

        0
0   10000
1   10000
2   10000
3   10000
4   10000
..    ...
95  10000
96  10000
97  10000
98  10000
99  10000

[100 rows x 1 columns]