In [1]:
import pandas as pd
import numpy as np

In [18]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_4/individual_results'

data = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/results_rank_{i}.csv'
    try:
        # Attempt to read the CSV file
        df = pd.read_csv(file_path, header=0)
    except FileNotFoundError:
        # If the file does not exist, skip to the next iteration
        print(f"File {file_path} not found. Skipping.")
        continue
    print("Number of Models in file", i, ":", len(df))
    data = pd.concat([data, df], ignore_index=True)

Number of Models in file 0 : 10000
Number of Models in file 1 : 10000
Number of Models in file 2 : 10000
Number of Models in file 3 : 10000
Number of Models in file 4 : 10000
Number of Models in file 5 : 10000
Number of Models in file 6 : 10000
Number of Models in file 7 : 10000
Number of Models in file 8 : 10000
Number of Models in file 9 : 10000
Number of Models in file 10 : 10000
Number of Models in file 11 : 10000
Number of Models in file 12 : 10000
Number of Models in file 13 : 10000
Number of Models in file 14 : 10000
Number of Models in file 15 : 10000
Number of Models in file 16 : 10000
Number of Models in file 17 : 10000
Number of Models in file 18 : 10000
Number of Models in file 19 : 10000
Number of Models in file 20 : 10000
Number of Models in file 21 : 10000
Number of Models in file 22 : 10000
Number of Models in file 23 : 10000
Number of Models in file 24 : 10000
Number of Models in file 25 : 10000
Number of Models in file 26 : 10000
Number of Models in file 27 : 10000
Number of Models in file 28 : 10000
Number of Models in file 29 : 10000
Number of Models in file 30 : 10000
Number of Models in file 31 : 10000
Number of Models in file 32 : 10000
Number of Models in file 33 : 10000
Number of Models in file 34 : 10000
Number of Models in file 35 : 10000
Number of Models in file 36 : 10000
Number of Models in file 37 : 10000
Number of Models in file 38 : 10000
Number of Models in file 39 : 10000
Number of Models in file 40 : 10000
Number of Models in file 41 : 10000
Number of Models in file 42 : 10000
Number of Models in file 43 : 10000
Number of Models in file 44 : 10000
Number of Models in file 45 : 10000
Number of Models in file 46 : 10000
Number of Models in file 47 : 10000
Number of Models in file 48 : 10000
Number of Models in file 49 : 10000
Number of Models in file 50 : 10000
Number of Models in file 51 : 10000
Number of Models in file 52 : 10000
Number of Models in file 53 : 10000
Number of Models in file 54 : 10000
Number of Models in file 55 : 10000
Number of Models in file 56 : 10000
Number of Models in file 57 : 10000
Number of Models in file 58 : 10000
Number of Models in file 59 : 10000
Number of Models in file 60 : 10000
Number of Models in file 61 : 10000
Number of Models in file 62 : 10000
Number of Models in file 63 : 10000
Number of Models in file 64 : 10000
Number of Models in file 65 : 10000
Number of Models in file 66 : 10000
Number of Models in file 67 : 10000
Number of Models in file 68 : 10000
Number of Models in file 69 : 10000
Number of Models in file 70 : 10000
Number of Models in file 71 : 10000
Number of Models in file 72 : 10000
Number of Models in file 73 : 10000
Number of Models in file 74 : 10000
Number of Models in file 75 : 10000
Number of Models in file 76 : 10000
Number of Models in file 77 : 10000
Number of Models in file 78 : 10000
Number of Models in file 79 : 10000
Number of Models in file 80 : 10000
Number of Models in file 81 : 10000
Number of Models in file 82 : 10000
Number of Models in file 83 : 10000
Number of Models in file 84 : 10000
Number of Models in file 85 : 10000
Number of Models in file 86 : 10000
Number of Models in file 87 : 10000
Number of Models in file 88 : 10000
Number of Models in file 89 : 10000
Number of Models in file 90 : 10000
Number of Models in file 91 : 10000
Number of Models in file 92 : 10000
Number of Models in file 93 : 10000
Number of Models in file 94 : 10000
Number of Models in file 95 : 10000
Number of Models in file 96 : 10000
Number of Models in file 97 : 10000
Number of Models in file 98 : 10000
Number of Models in file 99 : 10000

In [19]:
data

,m,n,o,num_images,pos_rms,mag_rms,avg_mag_per,chi2,source_x,source_y,...,SIE_y,SIE_e,SIE_$θ_{e}$,SIE_$r_{core}$,"PERT_$z_{s,fid}$",PERT_x,PERT_y,PERT_$\gamma$,PERT_$θ_{\gamma}$,PERT_$\kappa$
0,0.001,0.00000,0.0,1,0.028354,0.000000,0.000000,1534.77000,20.81103,20.79133,...,20.79135,3.715333e-06,19.375160,0.0,1.0,20.78,20.78,3.799288e-07,-2.323633,0.0
1,0.001,36.03604,0.0,4,0.021259,0.217763,146.751739,798.06960,20.80922,20.78340,...,20.78328,6.458669e-03,-22.885400,0.0,1.0,20.78,20.78,1.872246e-03,63.190360,0.0
2,0.001,72.07207,0.0,6,0.057982,0.189766,108.058849,1936.00900,20.80125,20.78450,...,20.78521,1.651851e-01,-35.099600,0.0,1.0,20.78,20.78,6.005241e-02,54.213150,0.0
3,0.001,108.10811,0.0,4,0.016403,0.212538,144.361955,721.87170,20.81058,20.78377,...,20.78128,1.750821e-02,-3.203857,0.0,1.0,20.78,20.78,1.644055e-05,120.241700,0.0
4,0.001,144.14414,0.0,1,0.031361,0.000000,0.000000,1535.02600,20.81127,20.79141,...,20.79143,9.531862e-07,30.701270,0.0,1.0,20.78,20.78,2.379148e-07,153.606600,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.100,215.85586,0.0,4,0.024001,0.209147,143.559401,1035.56500,20.80865,20.78491,...,20.78186,6.196525e-02,-31.203690,0.0,1.0,20.78,20.78,1.820297e-02,226.950700,0.0
999996,0.100,251.89189,0.0,4,0.615098,0.403380,167.131147,32.44649,20.80503,20.77870,...,20.77896,1.072923e-01,89.555130,0.0,1.0,20.78,20.78,3.757609e-02,359.549200,0.0
999997,0.100,287.92793,0.0,1,0.211863,0.000000,0.000000,1534.00300,20.81120,20.79123,...,20.79126,3.824744e-07,11.978750,0.0,1.0,20.78,20.78,4.434787e-05,290.984700,0.0
999998,0.100,323.96396,0.0,1,0.027942,0.000000,0.000000,1535.45800,20.81134,20.79117,...,20.79120,2.367965e-06,-9.425349,0.0,1.0,20.78,20.78,6.274726e-08,356.107000,0.0
999999,0.100,360.00000,0.0,6,0.017963,0.233087,197.190410,179.73300,20.81542,20.77717,...,20.77635,9.064841e-02,66.997380,0.0,1.0,20.78,20.78,3.177005e-02,337.263300,0.0

In [20]:
data.to_csv('/Volumes/T7 Shield/Simulation Output/System 1/Sim 8_FR.csv', index=False)

In [21]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_4/progress_status'

progress = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/worker_{i}.status'
    try:
        df = pd.read_csv(file_path, header=None)
    except FileNotFoundError:
        print(f"File {file_path} not found. Skipping.")
        continue
    progress = pd.concat([progress, df], ignore_index=True)

In [22]:
progress

        0
0   10000
1   10000
2   10000
3   10000
4   10000
..    ...
95  10000
96  10000
97  10000
98  10000
99  10000

[100 rows x 1 columns]