In [1]:
import pandas as pd
import numpy as np

In [16]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_4/individual_results'

data = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/results_rank_{i}.csv'
    try:
        # Attempt to read the CSV file
        df = pd.read_csv(file_path, header=0)
    except FileNotFoundError:
        # If the file does not exist, skip to the next iteration
        print(f"File {file_path} not found. Skipping.")
        continue
    print("Number of Models in file", i, ":", len(df))
    data = pd.concat([data, df], ignore_index=True)

Number of Models in file 0 : 10000
Number of Models in file 1 : 10000
Number of Models in file 2 : 10000
Number of Models in file 3 : 10000
Number of Models in file 4 : 10000
Number of Models in file 5 : 10000
Number of Models in file 6 : 10000
Number of Models in file 7 : 10000
Number of Models in file 8 : 10000
Number of Models in file 9 : 10000
Number of Models in file 10 : 10000
Number of Models in file 11 : 10000
Number of Models in file 12 : 10000
Number of Models in file 13 : 10000
Number of Models in file 14 : 10000
Number of Models in file 15 : 10000
Number of Models in file 16 : 10000
Number of Models in file 17 : 10000
Number of Models in file 18 : 10000
Number of Models in file 19 : 10000
Number of Models in file 20 : 10000
Number of Models in file 21 : 10000
Number of Models in file 22 : 10000
Number of Models in file 23 : 10000
Number of Models in file 24 : 10000
Number of Models in file 25 : 10000
Number of Models in file 26 : 10000
Number of Models in file 27 : 10000
Number of Models in file 28 : 10000
Number of Models in file 29 : 10000
Number of Models in file 30 : 10000
Number of Models in file 31 : 10000
Number of Models in file 32 : 10000
Number of Models in file 33 : 10000
Number of Models in file 34 : 10000
Number of Models in file 35 : 10000
Number of Models in file 36 : 10000
Number of Models in file 37 : 10000
Number of Models in file 38 : 10000
Number of Models in file 39 : 10000
Number of Models in file 40 : 10000
Number of Models in file 41 : 10000
Number of Models in file 42 : 10000
Number of Models in file 43 : 10000
Number of Models in file 44 : 10000
Number of Models in file 45 : 10000
Number of Models in file 46 : 10000
Number of Models in file 47 : 10000
Number of Models in file 48 : 10000
Number of Models in file 49 : 10000
Number of Models in file 50 : 10000
Number of Models in file 51 : 10000
Number of Models in file 52 : 10000
Number of Models in file 53 : 10000
Number of Models in file 54 : 10000
Number of Models in file 55 : 10000
Number of Models in file 56 : 10000
Number of Models in file 57 : 10000
Number of Models in file 58 : 10000
Number of Models in file 59 : 10000
Number of Models in file 60 : 10000
Number of Models in file 61 : 10000
Number of Models in file 62 : 10000
Number of Models in file 63 : 10000
Number of Models in file 64 : 10000
Number of Models in file 65 : 10000
Number of Models in file 66 : 10000
Number of Models in file 67 : 10000
Number of Models in file 68 : 10000
Number of Models in file 69 : 10000
Number of Models in file 70 : 10000
Number of Models in file 71 : 10000
Number of Models in file 72 : 10000
Number of Models in file 73 : 10000
Number of Models in file 74 : 10000
Number of Models in file 75 : 10000
Number of Models in file 76 : 10000
Number of Models in file 77 : 10000
Number of Models in file 78 : 10000
Number of Models in file 79 : 10000
Number of Models in file 80 : 10000
Number of Models in file 81 : 10000
Number of Models in file 82 : 10000
Number of Models in file 83 : 10000
Number of Models in file 84 : 10000
Number of Models in file 85 : 10000
Number of Models in file 86 : 10000
Number of Models in file 87 : 10000
Number of Models in file 88 : 10000
Number of Models in file 89 : 10000
Number of Models in file 90 : 10000
Number of Models in file 91 : 10000
Number of Models in file 92 : 10000
Number of Models in file 93 : 10000
Number of Models in file 94 : 10000
Number of Models in file 95 : 10000
Number of Models in file 96 : 10000
Number of Models in file 97 : 10000
Number of Models in file 98 : 10000
Number of Models in file 99 : 10000

In [17]:
data

,m,n,o,num_images,pos_rms,mag_rms,avg_mag_per,chi2,source_x,source_y,...,SIE_y,SIE_e,SIE_$θ_{e}$,SIE_$r_{core}$,"PERT_$z_{s,fid}$",PERT_x,PERT_y,PERT_$\gamma$,PERT_$θ_{\gamma}$,PERT_$\kappa$
0,0.001,0.00000,0.0,2,0.053043,376.358772,6502.068362,25257.800,0.049497,0.035134,...,0.035133,0.000009,20.483620,0.0,1.0,0.0,0.0,0.001,0.00000,0.0
1,0.001,36.03604,0.0,2,0.121723,170.694369,4501.976928,25389.430,0.049936,0.037126,...,0.036817,0.000008,0.592623,0.0,1.0,0.0,0.0,0.001,36.03604,0.0
2,0.001,72.07207,0.0,2,0.150935,85.149479,1107.617019,20831.390,0.147240,0.033746,...,0.033850,0.033600,-86.632100,0.0,1.0,0.0,0.0,0.001,72.07207,0.0
3,0.001,108.10811,0.0,2,0.091046,138.457933,4574.226499,24900.910,0.050607,0.033808,...,0.034219,0.000009,-15.417760,0.0,1.0,0.0,0.0,0.001,108.10810,0.0
4,0.001,144.14414,0.0,2,0.109115,183.140010,4596.562301,25149.890,0.049900,0.033650,...,0.034106,0.000010,-5.885398,0.0,1.0,0.0,0.0,0.001,144.14410,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.100,215.85586,0.0,2,0.127351,136.173107,4817.188915,21150.260,0.140557,-0.002467,...,0.011038,0.266836,-57.874410,0.0,1.0,0.0,0.0,0.100,215.85590,0.0
999996,0.100,251.89189,0.0,4,0.514961,16.277713,313.607396,24977.370,0.001297,0.091236,...,0.086751,0.290157,-26.303830,0.0,1.0,0.0,0.0,0.100,251.89190,0.0
999997,0.100,287.92793,0.0,4,0.047360,65.792379,698.558806,14590.250,0.074833,0.018309,...,0.018168,0.219889,25.289530,0.0,1.0,0.0,0.0,0.100,287.92790,0.0
999998,0.100,323.96396,0.0,4,0.049717,43.121199,651.049395,15685.100,0.056553,0.031550,...,0.025494,0.254817,50.198120,0.0,1.0,0.0,0.0,0.100,323.96400,0.0
999999,0.100,360.00000,0.0,4,0.013453,6.112597,167.637962,1390.073,0.078618,0.053135,...,0.047372,0.073275,-82.582970,0.0,1.0,0.0,0.0,0.100,360.00000,0.0

In [18]:
data.to_csv('/Volumes/T7 Shield/Simulation Output/System 2/Sim 4_absmags.csv', index=False)

In [13]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_2/progress_status'

progress = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/worker_{i}.status'
    try:
        df = pd.read_csv(file_path, header=None)
    except FileNotFoundError:
        print(f"File {file_path} not found. Skipping.")
        continue
    progress = pd.concat([progress, df], ignore_index=True)

In [15]:
progress

        0
0   10000
1   10000
2   10000
3   10000
4   10000
..    ...
95  10000
96  10000
97  10000
98  10000
99  10000

[100 rows x 1 columns]