In [18]:
import pandas as pd
import numpy as np

In [24]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_4/individual_results'

data = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/results_rank_{i}.csv'
    try:
        # Attempt to read the CSV file
        df = pd.read_csv(file_path, header=0)
    except FileNotFoundError:
        # If the file does not exist, skip to the next iteration
        print(f"File {file_path} not found. Skipping.")
        continue
    print("Number of Models in file", i, ":", len(df))
    data = pd.concat([data, df], ignore_index=True)

Number of Models in file 0 : 10000
Number of Models in file 1 : 10000
Number of Models in file 2 : 10000
Number of Models in file 3 : 10000
Number of Models in file 4 : 10000
Number of Models in file 5 : 10000
Number of Models in file 6 : 10000
Number of Models in file 7 : 10000
Number of Models in file 8 : 10000
Number of Models in file 9 : 10000
Number of Models in file 10 : 10000
Number of Models in file 11 : 10000
Number of Models in file 12 : 10000
Number of Models in file 13 : 10000
Number of Models in file 14 : 10000
Number of Models in file 15 : 10000
Number of Models in file 16 : 10000
Number of Models in file 17 : 10000
Number of Models in file 18 : 10000
Number of Models in file 19 : 10000
Number of Models in file 20 : 10000
Number of Models in file 21 : 10000
Number of Models in file 22 : 10000
Number of Models in file 23 : 10000
Number of Models in file 24 : 10000
Number of Models in file 25 : 10000
Number of Models in file 26 : 10000
Number of Models in file 27 : 10000
Number of Models in file 28 : 10000
Number of Models in file 29 : 10000
Number of Models in file 30 : 10000
Number of Models in file 31 : 10000
Number of Models in file 32 : 10000
Number of Models in file 33 : 10000
Number of Models in file 34 : 10000
Number of Models in file 35 : 10000
Number of Models in file 36 : 10000
Number of Models in file 37 : 10000
Number of Models in file 38 : 10000
Number of Models in file 39 : 10000
Number of Models in file 40 : 10000
Number of Models in file 41 : 10000
Number of Models in file 42 : 10000
Number of Models in file 43 : 10000
Number of Models in file 44 : 10000
Number of Models in file 45 : 10000
Number of Models in file 46 : 10000
Number of Models in file 47 : 10000
Number of Models in file 48 : 10000
Number of Models in file 49 : 10000
Number of Models in file 50 : 10000
Number of Models in file 51 : 10000
Number of Models in file 52 : 10000
Number of Models in file 53 : 10000
Number of Models in file 54 : 10000
Number of Models in file 55 : 10000
Number of Models in file 56 : 10000
Number of Models in file 57 : 10000
Number of Models in file 58 : 10000
Number of Models in file 59 : 10000
Number of Models in file 60 : 10000
Number of Models in file 61 : 10000
Number of Models in file 62 : 10000
Number of Models in file 63 : 10000
Number of Models in file 64 : 10000
Number of Models in file 65 : 10000
Number of Models in file 66 : 10000
Number of Models in file 67 : 10000
Number of Models in file 68 : 10000
Number of Models in file 69 : 10000
Number of Models in file 70 : 10000
Number of Models in file 71 : 10000
Number of Models in file 72 : 10000
Number of Models in file 73 : 10000
Number of Models in file 74 : 10000
Number of Models in file 75 : 10000
Number of Models in file 76 : 10000
Number of Models in file 77 : 10000
Number of Models in file 78 : 10000
Number of Models in file 79 : 10000
Number of Models in file 80 : 10000
Number of Models in file 81 : 10000
Number of Models in file 82 : 10000
Number of Models in file 83 : 10000
Number of Models in file 84 : 10000
Number of Models in file 85 : 10000
Number of Models in file 86 : 10000
Number of Models in file 87 : 10000
Number of Models in file 88 : 10000
Number of Models in file 89 : 10000
Number of Models in file 90 : 10000
Number of Models in file 91 : 10000
Number of Models in file 92 : 10000
Number of Models in file 93 : 10000
Number of Models in file 94 : 10000
Number of Models in file 95 : 10000
Number of Models in file 96 : 10000
Number of Models in file 97 : 10000
Number of Models in file 98 : 10000
Number of Models in file 99 : 10000

In [25]:
data

,m,n,o,num_images,pos_rms,mag_rms,avg_mag_per,chi2,source_x,source_y,...,POW_e,POW_$θ_{e}$,POW_$r_{Ein}$,POW_$\gamma$ (PWI),"PERT_$z_{s,fid}$",PERT_x,PERT_y,PERT_$\gamma$,PERT_$θ_{\gamma}$,PERT_$\kappa$
0,0.001,0.00000,0.0,4,0.081253,72.029821,813.207184,10978.040,0.134325,0.033035,...,0.039446,101.296400,0.415696,2.299981,1.0,0.0,0.0,0.006341,-108.724000,0.0
1,0.001,36.03604,0.0,4,0.077805,23.366240,368.805472,8245.191,0.104220,0.004713,...,0.051028,9.778410,0.437808,2.299992,1.0,0.0,0.0,0.012176,2.509039,0.0
2,0.001,72.07207,0.0,4,0.034028,13.060264,205.948607,8755.190,0.088106,0.029691,...,0.082762,-67.288080,0.474690,2.299998,1.0,0.0,0.0,0.050504,78.856120,0.0
3,0.001,108.10811,0.0,4,0.080071,36.911885,472.918842,10928.390,0.145721,0.028807,...,0.070854,-18.706020,0.414786,2.299992,1.0,0.0,0.0,0.039664,81.633120,0.0
4,0.001,144.14414,0.0,4,0.080357,53.515610,636.322283,10942.590,0.140625,0.034526,...,0.000498,31.967530,0.413928,2.299992,1.0,0.0,0.0,0.017903,90.176100,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.100,215.85586,0.0,4,0.080068,52.648837,626.347219,10936.650,0.139713,0.033528,...,0.007220,-36.861460,0.414762,2.299996,1.0,0.0,0.0,0.018814,267.413500,0.0
999996,0.100,251.89189,0.0,4,0.079043,49.482974,595.228755,10932.030,0.139795,0.033632,...,0.009839,-15.269780,0.415469,2.299999,1.0,0.0,0.0,0.021263,268.284000,0.0
999997,0.100,287.92793,0.0,4,0.083746,30.031699,434.266359,8157.598,0.109077,0.007138,...,0.114158,6.412451,0.438439,2.299997,1.0,0.0,0.0,0.008434,275.095300,0.0
999998,0.100,323.96396,0.0,4,0.080309,36.120776,467.316725,10915.430,0.146527,0.034647,...,0.065425,2.804153,0.414889,2.299996,1.0,0.0,0.0,0.040183,271.171000,0.0
999999,0.100,360.00000,0.0,4,0.034400,13.521889,211.848538,8670.187,0.088969,0.040550,...,0.082730,66.524660,0.473716,2.299993,1.0,0.0,0.0,0.047327,279.250800,0.0

In [26]:
data.to_csv('/Volumes/T7 Shield/Simulation Output/System 2/Sim 16_absmags.csv', index=False)

In [27]:
data_folder = '/Volumes/T7 Shield/Dump/Sim_4/progress_status'

progress = pd.DataFrame()

for i in range(100):
    file_path = f'{data_folder}/worker_{i}.status'
    try:
        df = pd.read_csv(file_path, header=None)
    except FileNotFoundError:
        print(f"File {file_path} not found. Skipping.")
        continue
    progress = pd.concat([progress, df], ignore_index=True)

In [28]:
progress

        0
0   10000
1   10000
2   10000
3   10000
4   10000
..    ...
95  10000
96  10000
97  10000
98  10000
99  10000

[100 rows x 1 columns]